disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "PathOf100X"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2 2006"
logo = "logo-mt.jpg"

[[params.author.links]]
x-twitter = "http://X.com/pathof100x"

[[params.author.links]]
instagram = "http://Instagram.com/pathof100x"

[[params.author.links]]
tiktok = "https://www.tiktok.com/@pathof100x?_r=1&_t=ZP-92Dp3hJviwR"

["params.author"]
image = "avatar.jpg"
name = "Martin Trades"
bio = " "
headline = "PathOf100X is my personal trading hub. I document my NQ and MNQ futures journey, break down my setups, and post the profits, losses, and lessons along the way. It is built on discipline, faith, and the belief that consistent learning compounds into exponential growth. This is my real process and mindset, shared to help traders sharpen theirs. The path to becoming 100x better, one trade at a time. Nothing here is financial advice."
